[Tests]
  # user has an FE, but not for the requested cell
  [./no_FET_for_cell]
    type = 'RunException'
    input = master.i
    expect_err = "Requested cell_id not in the passed tally. Check that the cell filter in "
                 "the tallies XML file contains the ID you're requesting"
    required_applications = 'BuffaloApp'
  [../]
[]
